---
- hosts: docs-2020
  become: yes
  gather_facts: no
  vars:
    ansible_python_interpreter: '/usr/bin/python'
    users:
    - name: znz
      github_user: znz
    - name: hsbt
      github_user: hsbt
    - name: okkez
      github_user: okkez
    - name: shugo
      github_user: shugo
    - name: sorah
      github_user: sorah
  tasks:
  - name: 'Add user'
    user:
      name: '{{ item.name }}'
      create_home: yes
      shell: '/bin/bash'
      groups: 'sudo'
      append: yes
    loop: '{{ users }}'
  - name: 'Create .ssh'
    file:
      path: '/home/{{ item.name }}/.ssh'
      state: directory
      mode: '0755'
      owner: '{{ item.name }}'
      group: '{{ item.name }}'
    loop: '{{ users }}'
  - name: 'Download ssh public keys'
    get_url:
      url: 'https://github.com/{{ item.github_user }}.keys'
      dest: '/home/{{ item.name }}/.ssh/authorized_keys'
      mode: '0644'
      owner: '{{ item.name }}'
      group: '{{ item.name }}'
    loop: '{{ users }}'
  - name: 'Allow passwordless sudo'
    lineinfile:
      dest: /etc/sudoers.d/local-users
      create: yes
      state: present
      regexp: '^{{ item.name }} '
      line: '{{ item.name }} ALL=(ALL) NOPASSWD:ALL'
      validate: 'visudo -cf %s'
    loop: '{{ users }}'
